name: 'test-dts'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - name: test dts
        run: yarn test-dts